language: node_js
node_js:
  - "9"
env:
  global:
    - DATABASE_TEST="mongodb://localhost/voting-app-testing"
    - SITE_NAME="Voting App"
    - NODE_ENV=test
services:
  - redis-server
  - mongodb
cache: yarn
before_script:
  - yarn build
  - yarn start --silent &
script:
  - yarn test --maxWorkers 4
  - $(npm bin)/cypress run --config videoRecording=true --record --key 1153505b-f176-448c-ba80-2d46068d5c56