language: node_js
node_js:
  - "10"
env:
  global:
    - DATABASE_TEST="mongodb://localhost:27017/voting-app-testing"
    - SITE_NAME="Voting App"
    - NODE_ENV=test
services:
  - mongodb
cache:
  directories:
    - "node_modules"
before_script:
  - npm run build
  - npm start --silent &
script:
  - npm test
  - $(npm bin)/cypress run --record false --key 1153505b-f176-448c-ba80-2d46068d5c56
