language: node_js
node_js:
  - "10"
env:
  global:
    - DATABASE_TEST="mongodb://localhost:27017/voting-app-testing"
    - SITE_NAME="Voting App"
    - NODE_ENV=test
services:
  - mongodb
cache:
  directories:
    - $HOME/.pnpm-store
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
  - pnpm -v
install:
  - pnpm install --shamefully-flatten
before_script:
  - pnpm build
  - pnpm start --silent &
script:
  - pnpm test --maxWorkers 4
  - $(pnpm bin)/cypress run --record --key 1153505b-f176-448c-ba80-2d46068d5c56
before_cache:
  - pnpm store prune
