version: "3"
services:
  web:
    build:
      context: ./.
      dockerfile: ./Dockerfile
    image: implaier/voting-app:latest
    ports:
    - "3000:3000"
    links:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - data-volume:/data/db
volumes:
  data-volume: {}