version: "3"
services:
  mongo:
    image: mongo:latest
    ports:
    - "27017:27017"
    volumes:
    - data-volume:/data/db
  redis:
    image: redis:latest
    ports:
    - "6379:6379"
volumes:
  data-volume: {}