import typescript from 'rollup-plugin-typescript2';

export default {
  input: `src/index.ts`,
  output: [{ file: 'public/dist/index.js', format: 'cjs', sourcemap: true }],
  plugins: [typescript()],
  external: [
    'http',
    'body-parser',
    'connect-flash',
    'connect-redis',
    'cors',
    'express',
    'express-session',
    'morgan',
    'passport',
    'path',
    'redis',
    'csurf',
    'helmet',
    'moment',
    'compression',
    'method-override',
    'hashids',
    'mongoose',
    'md5',
    'winston',
    'passport-local-mongoose',
    'validator',
    'lodash',
    'express-validator/check',
    'express-validator/filter',
    'bluebird',
  ],
};
